### ISSUE TITLE
Social share images not working

### ISSUE THREAD

**Issue by nickdunn** [5t3ph/11ty-netlify-jumpstart#13]
Love this repo, thanks for putting it together!

I'm using the social share generator code for my own site, pretty much as-is from yours with paths to my dist directory changed. All runs fine locally. But on Netlify I get this when it tries to spawn a browser:

    12:43:04 PM: (node:1381) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
    12:43:04 PM: [1392:1392:1008/114304.556246:ERROR:browser_main_loop.cc(1426)] Unable to open X display.

Is yours definitely working as-is? I have locked to exactly the same versions in package.json.

**Comment by 5t3ph** [comment]
Hi @nickdunn - yes, I actually use this on two other properties and I just re-ran the deploy of this site since it publishes itself to Netlify as well and [here is a successfully generated image](https://11ty-netlify-jumpstart.netlify.app/previews/about.png).

A search turned up that you may have to explicitly set `headless: true` (line 11 in the original script) - let me know if that resolves it!

**Comment by nickdunn** [comment]
> A search turned up that you may have to explicitly set headless: true (line 11 in the original script) - let me know if that resolves it!

That fixed it! I changed `headless: chromium.headless` to `headless: true` and we're rockin' and rollin'. Thanks for the heads up :-)
