### ISSUE TITLE
Generate social preview for main page

### ISSUE THREAD

**Issue by tskarhed** [5t3ph/11ty-netlify-jumpstart#7]
Hi, just wanted to thank you, this looks amazing! I just love the social preview feature!

Be it so - is it possible to generate a preview for the site itself, if you would link directly to the "home" page?

**Comment by 5t3ph** [comment]
Hi @tskarhed - you _may_ be able to do it by having the screenshot script point at the `public` directory instead of populating the separate social images template. I might look into how that would work for another project of mine, [StyleStage.dev](https://stylestage.dev). If I work it out, I'll let you know, or feel free to [tag me on Twitter](https://twitter.com/5t3ph) if you find the solution and maybe write about it! For this project, I'd like to keep it as is but I appreciate the feedback and I'm glad overall the starter is working for you!
