### ISSUE TITLE
Home has no image

### ISSUE THREAD

**Issue by Antonio-Laguna** [5t3ph/11ty-netlify-jumpstart#9]
Hey @5t3ph !

Great work here. I'm learning a lot of 11ty by looking at this jumpstart. Your idea with images is great!

However, I think there's a bug (shows on Netlify right now) in which the homepage (since it has no title) shows a file named like `.png`. 

I'd assume that something in this line would work:

```
{%- set pageSocialImg %}{{ meta.url }}/previews/{% if title %}{{ title | slugify }}{% else %}index{% endif %}.png{% endset -%}
```

I've also done it so it's possible to use Front Matter to disable this image just in case

**Comment by 5t3ph** [comment]
Good catch @Antonio-Laguna - in this case we're generating it as "home" but you were correct that we missed using it. The fix is merged 👍 I also updated the template so that the home page uses the `meta.siteDescription` in the image instead of the duplicate "byline" that said "Published on {{ meta.siteName }}"
